const names = window.prompt("Enter your name");
var age = window.prompt("Enter your age");
var school = window.prompt("Enter your school name");
var grade = window.prompt("Enter your grade");
var standard = window.prompt("Enter your class:");
document.write("Name: " + names + "<br>");
document.write("Age: " + age + "<br>");
document.write("School: " + school + "<br>");
document.write("Grade: " + grade + "<br>");
const values = [names, age, school, grade, standard];
const filledValues = values.filter((value) => value !== null && value !== "");
const final_value = (filledValues.length / values.length) * 100;
document.write("Progress: " + final_value + "%<br>");
const progressBar = document.createElement("progress");
progressBar.style.height = "4vh";
progressBar.style.backgroundColor= "green";
progressBar.style.border = "1px solid green";
progressBar.style.borderRadius = "30px";
progressBar.value = filledValues.length;
progressBar.max = values.length;
progress.style.width = "0%";
progressBar.style.width = "100%";
progressBar.style.position = "fixed";
document.body.appendChild(progressBar);
